### ISSUE TITLE
Hardcoded python path should be removed from service

### ISSUE THREAD

**Issue by maffettone** [NSLS-II-SST/sst-workers#3]
Currently the suitcase service is easily upgradable using the python script that is executed within. However, the python path is rigidly referenced because the system is unaware of `BS_ENV`. 

https://github.com/NSLS-II-SST/sst-workers/blob/cdb7d274f27b02a53654fbc0ff3f4c213a148c3c/services/bluesky-suitcase-worker.service#L15

Because the AST nor beamline scientist has the rights to copy the `.service` into `/etc/systemd/system`, this can create delays on bluesky upgrades. 

Either a config belongs in `/etc` somewhere, or these files should be part of an ansible job that expands the default environment to a hard path.

**Comment by mrakitin** [comment]
I think in the service file, we can have a static reference to the shell script, that would be aware of the `BS_ENV` each time it's restarted. We now have the `bsrun` script that can probably serve this purpose.

@tacaswell, do you remember how `bsrun` was supposed to be used?

**Comment by maffettone** [comment]
Thanks for picking this up! 
Turns out it is not an issue here, as RSOXS is using an old fixed env and treating this service as end of life. 
https://github.com/NSLS-II-SST/sst-workers/pull/4/commits/810d6e524c4d72e2e409667caf3eb6dd9b7708a5

This would still be good public knowledge though!
